version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@db:5432/subscriptions?sslmode=disable", "up"]
    restart: on-failure

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["./main"]

volumes:
  pgdata: